### ISSUE TITLE
🐛 [Bug Report] - Offhand attacks that occur while on-next-hit abilities such as Heroic Strike are queued should not suffer the dual wield to-hit penalty.

### ISSUE THREAD

**Issue by buggiestbugofallbugs** [Yatzii93/TBC5MAN-Bug-Tracker#151] opened 2021-12-08 05:55 UTC
# Decription: #
Dual wielding causes a chance to miss penalty but when on-next-hit abilities are queued it should be ignored, meaning if you have an ability like heroic strike queued your offhand hits should never miss if you have 9% hit rating.
# How it works: #
If your heroic strike is queued your offhand can miss
# How it should work: #
If your heroic strike is queued and you have 9% hit rating offhand hits should never miss
# Source - You need to provide a source as evidence: #
https://us.forums.blizzard.com/en/wow/t/wow-classic-era-%E2%80%9Cnot-a-bug%E2%80%9D-list-updated-april-22-2021/175887
This is a widely known thing on TBC Classic and it is on the "not-a-bug" list, meaning its blizzlike and not something they want to remove.
# Additional Information: #

**Comment by Yatzii93** [comment] 2022-01-02 18:01
So blizzard is saying it's not a bug? I'll accept their stance. Closing

**Comment by Tankdiehutte** [comment] 2022-12-22 11:32
Proof Video from 2007, how it should work (almost no misses over the whole fight ):
 https://www.warcraftmovies.com/movieview.php?id=42942
 
 Replication video:
 Even with Heroic strike being spammed the offhand misses ( verfehlen ). Easy to see in the shown recount details. Mainhand is only heroic strike (Heldenhafter Stoß) & Offhand is listed as Melee attacks ( Nahkampf). The hitchance of the character is 10,7% and in this sample its even missing more than the exspected 17,3%.
 https://youtu.be/9-snzhxxBQ8

**Comment by Tankdiehutte** [comment] 2022-12-22 11:40
Sth worth adding: It should work the same for cleave. (see 1:05 in the warcraft movie from 2007 )

**Comment by Socom12** [comment] 2023-02-10 17:33
This should be fixed since it's a big class bug, how it should work is how it worked in all of vanilla to when heroic strike was removed (Cataclysm).

**Closed** 2023-03-09 15:16 UTC
Labels: confirmed bug, fixed
