### ISSUE TITLE
🐛 [Bug Report] - Lady Vashj went to phase 3 while 1 beam was still active

### ISSUE THREAD

**Issue by DanielStankovic** [Yatzii93/TBC5MAN-Bug-Tracker#56] opened 2020-04-19 20:20 UTC
# Decription: #
During phase 2 on Lady Vashj, she became active and started phase 3 while one of the beams was still active. We wiped and did not make another try, so I am not sure if it would happen again or not. It did not happen until now though. 

# How it works: #
Lady Vashj became active and went to phase 3 as soon as we turned off 3 beams. The fourth beam was still active and tethered to her but she was moving around the room and using p3 spells and mechanics. We did not miss any cores (3/3). The beam that was left active was the north-west one when looking at the Lady from the entrance stairs. The adds continued incoming even after she became active but we wiped quickly, so not quite sure if they were the new ones or the ones already spawned at the bottom of the stairs. We wiped before the 4th tainted. After the wipe, she returned to the starting position as usual.

# How it should work: #
Lady Vashj should transition to phase 3 after all 4 beams are deactivated.

# Source - You need to provide a source as evidence: #
Nobody took a screenshot because the wipe happened quickly after she became active. 

# Additional Information: #

**Comment by Yatzii93** [comment] 2020-05-09 12:29
Closing this bug report for now considering I've never heard of this occurance happening since the raid released and it isn't something that can be replicated. If the problem happens again with some proof it can be reopened for an investigation.

**Closed by Yatzii93** 2020-05-09 12:29 UTC
Labels: requires replication

**Comment by Yatzii93** [comment] 2020-07-23 12:33
This was caused by a reset bug, with the old code if players released to quickly before the boss at reached it's home position, the generators would of not reset properly. However, the reset code will now trigger instantly on a group wipe, ensuring this issue doesn't happen to anyone in the future.
